version: '3.8'
services:
  app:
    image: asadel
    ports:
      - 8080:8080
    environment:
      - BASE_URL=http://localhost:8080/
      - DB_HOST=mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.18
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: